/// Flutter icons LoginButtonIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LoginButtonIcon
///      fonts:
///       - asset: fonts/LoginButtonIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LoginButtonIcon {
  LoginButtonIcon._();

  static const _kFontFam = 'LoginButtonIcon';
  static const String? _kFontPkg = null;

  static const IconData github_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
