version: "3"

services:
  client:
    container_name: MVstreamerClient
    build:
      context: .
      dockerfile: DockerFile
  volumes:
    - "./:/app"
    - "/app/node_modules"
  ports:
    - "8080:8080"
  stdin_open: true
  environment:
    - CHOKIDAR_USEPOLLING=true
  command: npm start
